name: Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate Documentation
      run: ./build_docs.sh
      env:
        DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    - name: Deploy Documentation
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: .DerivedData/Build/Products/Debug-iphoneos/Timekeeper.doccarchive