name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-11
    strategy:
      matrix:
        xcode_version:
        - 11.7   # Swift 5.2.4
        - 12.4   # Swift 5.3.2
        - 12.5.1 # Swift 5.4.2
        - 13.0   # Swift 5.5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: swift test
      env:
        DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
